### ISSUE TITLE
Rendering docstrings properly

### ISSUE THREAD

**Issue by hargoniX** [leanprover/doc-gen4#12]
Mathlib makes massive use of doc strings and mathematical symbols in its doc strings, we should be able to render this properly in the browser just like the current doc-gen can.

**Comment by xubaiw** [comment]
```
-- TODO: Check why modules can have multiple doc strings and add that later on
```

The module doc of Lean is scattered around the whole documentation (See [this](https://leanprover-community.github.io/mathlib_docs/data/ordmapordset.html) mathlib page for example), which varies from other languages like Rust.

However currently it's impossible to render scattered module doc since the `moduleDocExt` keeps plain `String`s without their position.
