### ISSUE TITLE
Escape html tag in equations

### ISSUE THREAD

**Issue by xubaiw** [leanprover/doc-gen4#35]
In this [page](http://localhost:8000/build/doc/Unicode/Includes.html), the left sidebar is missing and definitions after `Unicode.bidiMirroringStr` is quite small.

<img width="1552" alt="截屏2022-02-19 下午10 59 33" src="https://user-images.githubusercontent.com/20809612/154806396-ea630e6e-4e31-4c16-a855-827fbd1a1cfc.png">

Looking at the source code, the nav bar element is missing and there are nested <small> and <font> tag surrounding the definitions. This bug exists in earlier version of doc-gen4 so it's not the problem of docstring. But I also fail to find that in doc-gen4 source code.

<img width="1552" alt="截屏2022-02-19 下午10 59 58" src="https://user-images.githubusercontent.com/20809612/154806398-549db2b8-a81c-4669-b04e-1e91bc520255.png">

**Comment by xubaiw** [comment]
Screenshot from earlier 7d43c8317816bf900e4517e0af9fadd85a11d0cb build.
<img width="1552" alt="截屏2022-02-19 下午11 11 24" src="https://user-images.githubusercontent.com/20809612/154806703-c8dff36b-3012-41b0-82f1-64dae882d50b.png">

**Comment by hargoniX** [comment]
The small stuff is not generated by doc-gen itself @xubaiw, the issue here is that your input files such as UCD/NameList.txt in your Unicode package do contain HTML tags, since you are statically including this into your code the generated equations will in turn contain these tags as well which causes this visual bug.

This basically comes down to: If your equations contain HTML in a way that the browser can interpret as syntactically correct your stuff will be represented in a wrong way. I'm guessing this can be fixed by escaping stuff here but I'm entirely unsure how to do this.

**Comment by hargoniX** [comment]
An alternative could be a an attribute that explicitly tells doc-gen to not generate equations about the declaration that is about to follow. This would also be reasonable in some regions of Mathlib where the equations that are generated are just insanely huge and not helpful at all like e.g. here: https://leanprover-community.github.io/mathlib4_docs/Mathlib/Data/BinaryHeap.html#BinaryHeap.heapifyDown
