### ISSUE TITLE
request: for a file + folder with same name, give more screen real estate to the folder

### ISSUE THREAD

**Issue by hrmacbeth** [leanprover/doc-gen4#99]
Certain folders in the run of the current doc-gen on mathlib4 have associated HTML pages, for example, mathlib itself:
https://leanprover-community.github.io/mathlib4_docs/Mathlib.html
and Mathlib/Tactic/Linarith:
https://leanprover-community.github.io/mathlib4_docs/Mathlib/Tactic/Linarith.html
Not all folders have these HTML pages; I don't understand the selection mechanism.

In principle I suppose we could add text to these pages and make them useful.  However, I think it is better not to have them at all, because in the left sidebar display those folders are displayed with HTML links to the associated pages, which makes it hard to expand those folders -- one has to click on the small arrow to the left of the folder rather than the folder itself.

Could these HTML pages simply be disabled?

**Comment by hargoniX** [comment]
These folders have HTML pages because there exists both a Lean file *as well as* a folder for them. In the case of Mathlib and Linarith:
- https://github.com/leanprover-community/mathlib4/blob/master/Mathlib/Tactic/Linarith.lean
- https://github.com/leanprover-community/mathlib4/blob/master/Mathlib.lean

The idea is that since Lean does transitive imports, even if the file is empty you might be interested in what it imports (which is the case here) because then you know what you are actually importing by importing this specific file. It could also be that this "folder file" does contain actual declarations etc. itself, for example the Lean code generator has a file like this: https://leanprover-community.github.io/mathlib4_docs/Lean/Compiler/LCNF/Simp.html

That being said I do also get annoyed a little by the arrow thing for sure. I wasn't quite sure how to make build it in a way so both things work so back at the time I decided to just leave it this way because you can both obtain the information and it is somewhat usable I guess, if someone has an idea for how to build this in a prettier way feel free to suggest it / send a PR.

**Comment by hrmacbeth** [comment]
Aha, thanks!  I still don't love this behaviour but I do now understand it.

In the case of the top-level folders (Mathlib, Std, etc) the set of imports contains no useful information, right? (because it is enforced to be everything?).  So one could safely delete those links, which are also the worst offenders in blocking clickability.

I'm not sure what to do about the import-only files which function as the default import for an associated non-top-level folder.  Indeed, maybe we can crowdsouce an idea for how to display this in a prettier way.  I'll mention it on Zulip at some point (or feel free to preempt me).

**Comment by hargoniX** [comment]
It is sadly not enforced what the top level files contain. In the case of Mathlib it is just made to be so with a script, in theory a user could hide modules from being imported by default without issues. They could also have declarations in the top level file without issues. Especially in single file libraries that only do something very small this might be the case.

**Comment by hrmacbeth** [comment]
All good points.  I started a [Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Docs.20navigation).

**Comment by hargoniX** [comment]
Implemented as illustrated above, alternative implementations are still welcome!
